TeachingPlatform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('TeachingPlatform.users.urls')),
    path('', include('TeachingPlatform.schedules.urls')),
    path('', include('TeachingPlatform.projects.urls')),
    path('', include('TeachingPlatform.accounts.urls')),
]

TeachingPlatform/users/urls.py
from django.urls import path

from TeachingPlatform.users.views import HomeView, TeachersView, AddTeachersView, StudentsView, DeleteStudentView, \
    DeleteTeacherView, \
    EditTeacherView, StudentsListView

urlpatterns = [
    path("", HomeView.as_view(), name='home_temp'),
    path("teachers/", TeachersView.as_view(), name='all_teachers_list'),
    path("add_teachers/", AddTeachersView.as_view(), name='teachers_add'),
    path("students/", StudentsView.as_view(), name='all_students_list'),
    path("students_list/<int:teacher_id>", StudentsListView.as_view(), name='students_list'),
    path("students_del/<int:student_id>", DeleteStudentView.as_view(), name='students_del'),
    # path("students_dash/<int:student_id>", StudentDashboardView.as_view(), name='students_dashboard'),
    path("teachers_del/<int:teacher_id>", DeleteTeacherView.as_view(), name='teachers_del'),
    path("teachers_edit/<int:teacher_id>", EditTeacherView.as_view(), name='teachers_edit'),
]

api/urls.py
from django.urls import path
from .views import ProjectView, ProjectAssignmentView, ScheduleSerializerView, SubjectSerializerView, \
    StudentSerializerView, TeacherSerializerView

urlpatterns = [
    path('projects', ProjectView.as_view()),
    path('projectassignment', ProjectAssignmentView.as_view()),
    path('schedule', ScheduleSerializerView.as_view()),
    path('subject', SubjectSerializerView.as_view()),
    path('student', StudentSerializerView.as_view()),
    path('teacher', TeacherSerializerView.as_view()),
]

TeachingPlatform/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from TeachingPlatform.users.managers import CustomUserManager

LESSON_TYPE = (
    ("B", "Backend"),
    ("F", "Frontend"),
    ("D", "Devops"),
    ("S", "System Administration"),
    ("C", "Cloud Engineering"),
)


class CustomUser(AbstractUser):
    email = models.EmailField("email address", unique=True)
    username = None

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS: list[str] = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Teacher(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    specialization = models.CharField(max_length=128, choices=LESSON_TYPE)
    email = models.EmailField(max_length=256)

    def __str__(self):
        return f"{self.first_name}, {self.last_name}, {self.get_specialization_display()}"


class Student(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    date_joined = models.DateField()
    email = models.EmailField(max_length=256)
    lesson_type = models.CharField(max_length=1, choices=LESSON_TYPE)
    teacher = models.ManyToManyField(Teacher, related_name='student_rel')

    def __str__(self):
        return f"{self.first_name}, {self.last_name}, {self.get_lesson_type_display()}"

projects/models.py
from django.db import models

from subjects.models import Subject
from users.models import Student, Teacher


class Project(models.Model):
    name = models.CharField(max_length=128, null=False) # null necessary?
    description = models.TextField()
    date_added = models.DateField()
    accepted_teachers = models.ManyToManyField(Teacher)
    requirements = models.ManyToManyField(Subject)

    def __str__(self):
        first_teacher = self.accepted_teachers.first()
        first_requirements = self.requirements.first()
        return f"{self.name} {self.date_added} {first_teacher.first_name} " \
               f"{first_teacher.last_name} {first_requirements.name}"


class ProjectAssignment(models.Model):
    date_assigned = models.DateField()
    deadline = models.DateField()
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    supervisor = models.ManyToManyField(Teacher)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        first_supervisor = self.supervisor.first()
        return f"{self.project.name} {self.student} {first_supervisor.first_name} {first_supervisor.last_name} {self.date_assigned} {self.deadline}"

TeachingPlatform/users/views.py
from django.shortcuts import render, redirect
from django.views import View

from TeachingPlatform.users.models import Teacher, Student


class HomeView(View):
    def get(self, request):
        context = {}
        return render(request, "users/home.html", context)


class TeachersView(View):
    def get(self, request):
        teachers = Teacher.objects.all()
        context = {'teachers': teachers}
        return render(request, "users/teachers.html", context)


class AddTeachersView(View):
    def get(self, request):
        context = {}
        return render(request, "users/add_teachers.html", context)

    def post(self, request):
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
        specialization = request.POST.get("techs")

        if Teacher.objects.filter(email=email).first():
            return render(request, "users/add_teachers.html", context={"error": "Email already exists!"})

        Teacher.objects.create(first_name=first_name, last_name=last_name, email=email, specialization=specialization)

        return redirect('teachers_list')


class DeleteTeacherView(View):
    def get(self, request, teacher_id):
        teacher = Teacher.objects.get(id=teacher_id)
        teacher.delete()
        return redirect('teachers_list')


class StudentsView(View):
    def get(self, request):
        students = Student.objects.all()
        context = {'students': students}
        return render(request, "users/students.html", context)


class StudentsListView(View):
    def get(self, request, teacher_id):
        teacher = Teacher.objects.get(id=teacher_id)
        students = teacher.student_rel.all()
        context = {'teacher': teacher, 'students': students}
        return render(request, 'users/students_list.html', context)


class DeleteStudentView(View):
    def get(self, request, student_id):
        student = Student.objects.get(id=student_id)
        student.delete()
        return redirect('students_list')


class EditTeacherView(View):
    def get(self, request, teacher_id):
        teacher = Teacher.objects.get(id=teacher_id)
        context = {'teacher': teacher}
        return render(request, "users/edit_teacher.html", context)

    def post(self, request, teacher_id):
        teacher = Teacher.objects.get(id=teacher_id)

        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        specialization = request.POST.get("techs")

        teacher.first_name = first_name
        teacher.last_name = last_name
        teacher.specialization = specialization
        teacher.save()

        return redirect('teachers_list')


# class StudentDashboardView(View):
#     def get(self, request, student_id):
#         students = Student.objects.get(id=student_id)
#         context = {'students': students}
#         return render(request, "users/students_dashboard.html", context)

TeachingPlatform/users/templates/users/add_teachers.html
{% extends 'main.html' %}

{% block content %}

    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="validationDefault01">First name</label>
                <input type="text" class="form-control" id="validationDefault01" placeholder="First name"
                       name="first_name"
                       required>
            </div>
            <div class="col-md-4 mb-3">
                <label for="validationDefault02">Last name</label>
                <input type="text" class="form-control" id="validationDefault02" placeholder="Last name"
                       name="last_name"
                       required>
            </div>
            <div class="col-md-4 mb-3">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                       name="email"
                       placeholder="Enter email">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                    else.</small>
            </div>
            <div class="col-md-4 mb-3">
                <label for="Specializations">Specialization:</label>
                <select name="techs" id="Specializations">
                    <option value="B">Backend</option>
                    <option value="F">Frontend</option>
                    <option value="D">Devops</option>
                    <option value="S">System Administration</option>
                    <option value="C">Cloud Engineering</option>
                </select>
            </div>

        </div>
        <button class="btn btn-primary" type="submit">Add</button>
    </form>

    {% if error %}
    <div class="alert alert-danger alert-dismissible fade show col-lg-3" role="alert">
        {{ error }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}

{% endblock %}

TeachingPlatform/users/templates/users/edit_teacher.html
{% extends 'main.html' %}

{% block content %}

    <h3>Teacher: {{ teacher.first_name }} {{  teacher.last_name  }}</h3>
    <p>Email {{ teacher.email }} </p>

    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="validationDefault01">First name</label>
                <input type="text" class="form-control" id="validationDefault01" placeholder="First name"
                       name="first_name" value="{{ teacher.first_name }}"
                       onfocus="if (this.value === '{{ teacher.first_name }}') {this.value = '';}"
                       onblur="if (this.value === '') {this.value = '{{ teacher.first_name }}';}"
                >
            </div>
            <div class="col-md-4 mb-3">
                <label for="validationDefault02">Last name</label>
                <input type="text" class="form-control" id="validationDefault02" placeholder="Last name"
                       name="last_name" value="{{ teacher.last_name }}"
                       onfocus="if (this.value === '{{ teacher.last_name }}') {this.value = '';}"
                       onblur="if (this.value === '') {this.value = '{{ teacher.last_name }}';}"
                >

            </div>
            <div class="col-md-4 mb-3">
                <label for="Specializations">Specialization:</label>
                <select name="techs" id="Specializations">
                    <option value="B">Backend</option>
                    <option value="F">Frontend</option>
                    <option value="D">Devops</option>
                    <option value="S">System Administration</option>
                    <option value="C">Cloud Engineering</option>
                </select>
            </div>

        </div>
        <button class="btn btn-primary" type="submit">Modify</button>
    </form>
{% endblock %}

TeachingPlatform/users/templates/users/home.html
{% extends 'main.html' %}

{% block content %}
<div class="container">
    <div class="align-items-center justify-content-center">
        <h1 class="text-center" style="font-size: 60px; font-family: fantasy">
            Welcome to our teaching platform
        </h1>
    </div>
</div>
{% endblock content %}

TeachingPlatform/users/templates/users/students.html
{% extends 'main.html' %}

{% block content %}

    <div class="container">
        <div class="h-100 d-flex" style="padding-top: 20px;">
            <div>
                <table class="table">
                    <tr class="bg-secondary">
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Tech</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                    </tr>
                    <tbody>
                    {% for student in students %}
                        <tr>
                            <td>{{ student.first_name }}</td>
                            <td>{{ student.last_name }}</td>
                            <td>{{ student.email }}</td>
                            <td>{{ student.get_lesson_type_display }}</td>
                            <td><a href="#">Edit</a></td>
                            <td><a href="{% url 'students_del' student.id %}">Delete</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

TeachingPlatform/users/templates/users/students_dashboard.html
{% extends 'main.html' %}

{% block content %}

    <div class="container">
        <div class="h-100 d-flex" style="padding-top: 20px;">
            <div>
                <h3>Student: {{ students.first_name }} {{ students.last_name }}</h3>
                <h1>Date joined: {{ students.date_joined }}</h1>
                <table class="table">
                    <tr class="bg-secondary">
                        <th scope="col">Project</th>
                        <th scope="col">Description</th>
                        <th scope="col">Deadline</th>
                    </tr>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

TeachingPlatform/users/templates/users/students_list.html
{% extends 'main.html' %}

{% block content %}

    <div class="container">
        <div class="h-100 d-flex" style="padding-top: 20px;">
            <div>
                <h3>Teacher: {{ teacher.first_name }} {{ teacher.last_name }}</h3>
                <table class="table">
                    <tr class="bg-secondary">
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Projects</th>
                    </tr>
                    <tbody>
                    {% for student in students %}
                        <tr>
                            <td>{{ student.first_name }}</td>
                            <td>{{ student.last_name }}</td>
                            <td>{{ student.email }}</td>
                            <td>
                                {% for assignment in student.projectassignment_set.all %}
                                    {{ assignment.project.name }}<br>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

TeachingPlatform/users/templates/users/teachers.html
{% extends 'main.html' %}

{% block content %}

    <div class="container">
        <div class="h-100 d-flex" style="padding-top: 20px;">
            <div>
                <table class="table">
                    <tr class="bg-secondary">
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Specialization</th>
                        <th scope="col">Modify</th>
                        <th scope="col">Delete</th>
                        <th scope="col">Students</th>
                    </tr>
                    <tbody>
                    {% for teacher in teachers %}
                        <tr>
                            <td>{{ teacher.first_name }}</td>
                            <td>{{ teacher.last_name }}</td>
                            <td>{{ teacher.email }}</td>
                            <td>{{ teacher.get_specialization_display }}</td>
                            <td class="text-md-center">
                                <a href="{% url 'teachers_edit' teacher.id %}">Edit</a>
                            </td>
                            <td class="text-md-center">
                                <a href="{% url 'teachers_del' teacher.id %}">Del</a>
                            </td>
                            <td class="text-md-center">
                                <a href="{% url 'students_list' teacher.id %}">List</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}